AdidasNew/Models/DomainModels/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AdidasNew.Models.DomainModels
{
    public class Question
    {
        [Key]
        public int Id { get; set; }

  
        [MaxLength(200)]
        public string question { get; set; }

        public int Level { get; set; }

        public int TypeQuestion { get; set; }

        public bool IsChange { get; set; }

        public bool IsDelete { get; set; }
        [MaxLength(20)]
        public string Creator { get; set; }

    }
}

AdidasNew/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdidasNew.Models.EntityModels;
using AdidasNew.Models.Repositores;
using AdidasNew.ViewModels;


namespace AdidasNew.Controllers
{
    public class HomeController : Controller
    {
        private AdidasNew.Models.DomainModels.DatabaseContext db = null;
        public static int personId;
        public ActionResult Index()
        {
            
            return RedirectToAction("DashBorad", "Admin");
        }

        [Authorize]
        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        [HttpGet]
        [AllowAnonymous]
        public ActionResult Register()
        {
            DateOfBirth date = new DateOfBirth();
            ViewBag.Day = date.DayList;
            ViewBag.Month = date.MonthList;
            ViewBag.Year = date.YearList;



            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public ActionResult Register(PersonInfo per, HttpPostedFileBase UploadImage)
        {
            var yt = ModelState.IsValid;
            personId = 0;
            per.Person.BirthDay = (per.Date.Year + "/" + per.Date.Month + "/" + per.Date.Day).ToGeorgianDateTime();
            per.Person.RegPerson = DateTime.Now;



            //------------------------------------------------Image----------------------------------------------------------
            string AllowFormat = "image/jpeg,image/png,image/jpg,image/jpeg";
            if (UploadImage != null && UploadImage.ContentLength > 0)
            {
                if (!AllowFormat.Split(',').Contains(UploadImage.ContentType))
                {
                    return MessageBox.Show(" فرمت عکس صحیح نیست", MessageType.Warning);
                }
                else
                {
                    var yy = UploadImage.InputStream.ResizeImageByHeight(700, utilty.ImageComperssion.Normal);
                    // UploadImage.InputStream.ResizeImageByHeight(500, @"E:\1\" + UploadImage.FileName);
                    per.Person.image = yy;
                }

            }
            else
            {
                return MessageBox.Show(" عکس انتخاب نشده است", MessageType.Warning);
            }

            //--------------------------------------------------------------------------------------------------------------------------


            per.Person.NationalCode = per.Person.NationalCode.ConvertNumbersToEnglish();
            per.Person.Mobile = per.Person.Mobile.ConvertNumbersToEnglish();
            per.Person.Tell = per.Person.Tell.ConvertNumbersToEnglish();
            //per.Person.SalaryExpection = per.Person.SalaryExpection.Replace(",", string.Empty).ConvertNumbersToEnglish();
            per.Person.SalaryExpection = per.Person.SalaryExpection.ConvertNumbersToEnglish();
            per.Person.Status = 0;

            PersonRepository blPerson = new PersonRepository();
            JobRecordRepository blJob = new JobRecordRepository();
            RelationShipRepository blRelation = new RelationShipRepository();

            if (blPerson.Add(per.Person))
            {
                per.JobRecord1.Person_FK = personId;
                per.JobRecord2.Person_FK = personId;
                per.JobRecord3.Person_FK = personId;

                per.RelationShip1.Person_FK = personId;
                per.RelationShip2.Person_FK = personId;
                per.RelationShip3.Person_FK = personId;

                if (per.JobRecord1.Company != null)
                    blJob.Add(per.JobRecord1);
                if (per.JobRecord2.Company != null)
                    blJob.Add(per.JobRecord2);
                if (per.JobRecord3.Company != null)
                    blJob.Add(per.JobRecord3);

                if (per.RelationShip1.Name != null)
                    blRelation.Add(per.RelationShip1);
                if (per.RelationShip2.Name != null)
                    blRelation.Add(per.RelationShip2);
                if (per.RelationShip3.Name != null)
                    blRelation.Add(per.RelationShip3);

                return MessageBox.Show("با موفقیت ثبت شد", MessageType.Success);
            }

            else
                return MessageBox.Show(" ثبت نشد", MessageType.Error);
            //return View();
        }

    }
}

AdidasNew/Controllers/MobileAppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AdidasNew.Models.Repositores;
using AdidasNew.ViewModels;
using AdidasNew.Models.DomainModels;

namespace AdidasNew.Controllers
{
    public class MobileAppController : Controller
    {
      public static  bool isvalid = false;
        public static string creator = "";
        public static int tempPage =1;
        QuestionRepository db = new QuestionRepository();
        // GET: MobileApp
        [HttpGet]
        public ActionResult Index()
        {
            isvalid = false;
            return View();
        }


        [HttpPost]
        public ActionResult Index(TempUser user)
        {
            string distnace = "home";
            if(user.Username.ToLower()=="kosar"&user.Password=="137705")
            {
                isvalid = true;
                creator = "کوثر";
                return RedirectToAction(distnace);
                
            }
            else if (user.Username.ToLower() == "ali" & user.Password == "136911")
            {
                isvalid = true;
                creator = "علی";
                return RedirectToAction(distnace);
            }
            else if (user.Username.ToLower() == "javad" & user.Password == "13733")
            {
                isvalid = true;
                creator = "جواد";
                return RedirectToAction(distnace);
            }
            else if (user.Username.ToLower() == "zohreh" & user.Password == "13623")
            {
                isvalid = true;
                creator = "دیانا";
                return RedirectToAction(distnace);
            }
            else if (user.Username.ToLower() == "mansour" & user.Password == "136815")
            {
                isvalid = true;
                creator = "منصور";
                return RedirectToAction(distnace);
            }
            else
            {
                ViewBag.massage = " نام کاربری یا رمز عبور اشتباه است";
                return View();
            }
 
        }

        [HttpGet]
        public ActionResult home()
        {
            if(isvalid)
            return View();
            else
                return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult NewQuestion(int id=0)
        {
            if (isvalid)
                if(id==0)
                {
                    ViewBag.back = "home";
                    return View(new Question() { Id=0});

                }

            else
                {
                    ViewBag.back = "../../MobileApp/Questions/" + tempPage;
                    var q = db.Find(id);
                    return View(q);
                }
            else
                return RedirectToAction("Index");
        }
        [HttpPost]
        public ActionResult NewQuestion(Question q )
        {
            if(q.Id==0)
            {
                ViewBag.back = "../../MobileApp/home";
                q.Creator = creator;
                if (db.Add(q))
                    ViewBag.Success = "سوال با موفقیت ثبت شد";
                return View(new Question() { Id = 0 });
            }
            else
            {
                q.Creator = creator;
                ViewBag.back = "../../MobileApp/Questions/" + tempPage;
                if (db.Update(q))
                    ViewBag.Success = "سوال با موفقیت ویرایش شد";
                return View(q);
            }

        }

        public ActionResult Questions(int id=1)
        {
            tempPage = id;
            if (isvalid)
            {
                int take = 10;
                int skip = (id-1)*take;
                int count = db.Count();

                ViewBag.pageId = id;
                if(count%3==0)
                    ViewBag.pageCount = count / take;
                else
                    ViewBag.pageCount = count / take+1;


                var list = db.Select().OrderByDescending(p=>p.Id).Skip(skip).Take(take).ToList();
                return View(list);
            }

            else
                return RedirectToAction("Index");
        }

    }
}

AdidasNew/Views/MobileApp/Index.cshtml
@model AdidasNew.ViewModels.TempUser
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />


</head>
<body class="loginPage wrapper">

    <div style="direction: ltr;">

        <div class="row">

            <div class="">
                <section class="loginForm" id="loginForm">
                    <h2 style="text-align: center;font-family: 'BTitrBd' !important;color: #0B0B61">صفحه ورود</h2>
                    @using (Html.BeginForm("Index", "MobileApp", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                    {
                        @Html.AntiForgeryToken()
                        @*<h4>Use a local account to log in.</h4>*@
                        <hr />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            <div class="col-xs-12" style="text-align: right;">
                                @Html.TextBoxFor(m => m.Username, new { @class = "form-control login-text", @placeholder = "نام کاربری", style = "direction: rtl;" })
                            </div>



                        </div>
                        <div class="form-group">
                            <div class="col-xs-12" style="text-align: right;">
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control login-text", @placeholder = "رمز عبور", style = "direction: rtl;" })

                            </div>



                        </div>

                        <div class="form-group">
                            <div class=" col-md-12" style="display: flex;justify-content: center;">
                            <div style="color:darkred">@ViewBag.massage</div>
                            </div>
                        </div>


                        <div class="form-group">
                            <div class=" col-md-12" style="display: flex;justify-content: center;">
                                <input type="submit" value="ورود" class="btn btn-default" />
                            </div>
                        </div>

                    }
                </section>
            </div>


        </div>

    </div>

</body>
</html>

AdidasNew/Views/MobileApp/NewQuestion.cshtml
@model AdidasNew.Models.DomainModels.Question

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NewQuestion</title>
    <link href="~/Content/bootstrap.min.darkly.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <style>
        .wrapper {
            height: 100vh;
        }

        .loginForm {
            max-width: 600px;
            direction: rtl;
            padding: 10px 50px 100px 50px;
        }

        .lbl {
            color: black;
            text-align: right;
        }
    </style>

</head>
<body class=" wrapper">

    <div class="loginForm">
        @using (Html.BeginForm("NewQuestion", "MobileApp", FormMethod.Post, new { enctype = "multipart/form-data", id = "myUploadForm" }))
        {
            <div style="display:flex; justify-content:center; margin-bottom:20px;">
                <img src="~/Models/Repositores/question-marks.jpg" class="rounded-circle" width="200" height="200" alt="Cinque Terre">
            </div>

            <div class="col-lg-12">

                <div class="lbl">@Html.Label("سوال جدید را وارد کنید")</div>

                <p>
                    @Html.TextBoxFor(p => p.question, new { @class = "form-control", id = "txtquestion" })
                </p>
            </div>

            <div class="col-sm-4">
                <div class="lbl">
                    @Html.Label("سطح سوال")
                </div>
                <div id="salam" class="form-group">
                    @Html.DropDownListFor(p => p.Level, DropDown.GetStatusQuestion(), new { @class = "form-control _dropdown", style = " display: inline;" })
                </div>
            </div>

            <div class="form-group">
                <div id="messageSuccess" class=" col-sm-12" style="color:darkgreen;text-align:center;height:30px;width:100%;">
                    @ViewBag.Success
                </div>
            </div>
            <div class="form-group">
                <div class=" col-md-12 d-flex justify-content-around">
                    <input type="submit" value="ثبت سوال" class="btn btn-success" id="btnsend" />
                    <a href= "@ViewBag.back" class="btn  btn-primary"> بازگشت</a>
                </div>
            </div>
        }

    </div>


    <script>
        var send = true;

        $(document).ready(function () {
            $("#txtquestion").val("");

             if (@Model.Id!== 0) {
             $("#txtquestion").val("@Model.question");
                 $("#txtquestion").css("color", "blue");
                 $("select").val(@Model.Level);
                 $("#btnsend").val("ویرایش");
        }
        });


        $("#btnsend").click(function (evt) {

             if (send == false) {
                   evt.preventDefault();
            }
            if ($("#txtquestion").val() == "") {
                evt.preventDefault();
            }


        });

        $("#txtquestion").focus(function () {
            $("#messageSuccess").text("");
        });

        $("form").submit(function () {
            send = false;
        });

    </script>

</body>
</html>

AdidasNew/Views/MobileApp/Questions.cshtml
@model IEnumerable<AdidasNew.Models.DomainModels.Question>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Questions</title>
    <link href="~/Content/bootstrap.min.darkly.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <style>
        .mytable {
            direction: rtl;
            text-align: center;
        }
    </style>
</head>
<body>

    <div class="container">
        <table class="table table-info table-hover mytable">
            <thead>
                <tr>
                    <th scope="col">ردیف</th>
                    <th scope="col">سوال</th>
                    <th scope="col">سطح</th>
                    <th scope="col">طراح</th>
                    <th scope="col">ویرایش</th>


                </tr>
            </thead>
            <tbody>
                @{
                    int i = 1;
                    foreach (var item in Model)
                    {
                        <tr class="@(i % 2 == 0 ? " table-primary" : " table-dark ")">

                            <td>@i</td>
                            <td>@item.question</td>
                            <td>
                                @switch (@item.Level)
                                {
                                    case 1:
                                        <span> آسان</span>
                                        break;
                                    case 2:
                                        <span> متوسط</span>
                                        break;
                                    case 3:
                                        <span> سخت</span>
                                        break;

                                }
                            </td>
                            <td>@item.Creator</td>
                            <td>
                                <a href="~/qu/edit/@item.Id" class="btn  btn-info"> ویرایش</a>
                            </td>
                        </tr>
                        i = i + 1;
                    }
                }


            </tbody>
        </table>



        <div class="row d-flex justify-content-around">
            <ul class="pagination pagination-lg">
                <li class="page-item  @(((int)ViewBag.pageId == 1) ? "disabled" : "")  ">
                    <a class="page-link" href="#">&laquo;</a>
                </li>
                <li class="page-item @(((int)ViewBag.pageId == 1) ? "active" : "") ">
                    <a class="page-link" href=" ~/MobileApp/Questions/1">1</a>
                </li>
                @{
                    var pagenumer = (int)ViewBag.pageId;
                    if ((int)ViewBag.pageId != 1& (int)ViewBag.pageId!=2)
                    {
                        <li class="page-item ">
                            <a class="page-link" href="#">...</a>
                        </li>

                    }
                    else
                    {
                        pagenumer = 2;
                    }

                    for (int iii = pagenumer; iii < (int)ViewBag.pageId + 4 & iii < (int)ViewBag.pageCount; iii++)
                    {
                        <li class="page-item   @(iii==((int)ViewBag.pageId ) ? "active" : "") ">
                            <a class="page-link" href=" ~/MobileApp/Questions/@iii">@iii</a>
                        </li>
                    }

                    if ( (int)ViewBag.pageCount- (int)ViewBag.pageId>4)
                    {
                        <li class="page-item ">
                            <a class="page-link" href="#">...</a>
                        </li>
                    }
                }
                <li class="page-item  @(((int)ViewBag.pageId==(int)ViewBag.pageCount)?"active":"") ) ">
                    <a class="page-link" href=" ~/MobileApp/Questions/@ViewBag.pageCount">@ViewBag.pageCount</a>
                </li>
                <li class="page-item @(((int)ViewBag.pageId==(int)ViewBag.pageCount)?"disabled":"") ">
                    <a class="page-link" href=" ~/MobileApp/Questions/(@ViewBag.pageCount-1)">&raquo;</a>
                </li>

            </ul>


        </div>
        <div class="row d-flex justify-content-around">
            @Html.ActionLink("بازگشت", "home",null,new { @class = "btn  btn-info" })
        </div>

    </div>


</body>
</html>

AdidasNew/Views/MobileApp/home.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>home</title>
    <link href="~/Content/bootstrap.min.darkly.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <style>
        .wrapper {
            height: 100vh;            
        }
        .buttomm {
            height: 200px;
            margin: 25px;
            display: flex;
            align-content: center;
            justify-content: center;
            width: 100%;
        }
        .card {
            width: 100%;
            text-align: center;
            font-family: 'BMitraBold' !important;
        }
    </style>
</head>
<body class="wrapper">
    <div class="row" style="width:600px;">
        <div class="col-sm-5  ">
            <a href="~/MobileApp/NewQuestion" class="buttomm">
                <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                    <div class="card-header"></div>
                    <div class="card-body">
                        <h4 class="card-title">طرح سوالات جدید</h4>
                    </div>
                </div>
            </a>
        </div>
        <div class="col-sm-5  ">
            <a href="~/MobileApp/Questions" class="buttomm">
                <div class="card text-white bg-primary mb-3" style="max-width: 20rem;">
                    <div class="card-header"></div>
                    <div class="card-body">
                        <h4 class="card-title">بانک سوالات</h4>
                        <p class="card-text">مشاهده و یرایش </p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</body>
</html>